### ISSUE TITLE
Question on cropping and alignment

### ISSUE THREAD

**Issue by vandana-rajan** [kuhnkeF/ABAW2020TNT#1]
Hi,

Thanks a lot for sharing your code. 

This is not an issue but rather a question. 

The challenge provides cropped and aligned face images. Then why did you have to use a separate face detector+cropping+alignment mechanism? Is it only for generating the mask images or does it have to do with better synchronization with audio stream?

Thanks in advance,

**Comment by kuhnkeF** [comment]
Hi,

our main motivation was to have access to higher image resolution and improved assignment of people to the detections. A lot of videos contain several people and we were unhappy with the assignments found in the provided data. Mask images and control over audio synchronization just turned out to be useful in a later stage :-) 
We did not evaluate if audio synchronization is an issue. In my experience, sync that is off a frame or two should not deteriorate the results.

**Comment by vandana-rajan** [comment]
Thanks for the clarification.
